-- Run this script once in the Supabase SQL Editor.
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text not null default '',
  icon text not null default 'book-open',
  display_order integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete cascade,
  name text not null,
  slug text not null unique,
  description text not null default '',
  display_order integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  content text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_answer text not null check (correct_answer in ('A', 'B', 'C', 'D')),
  explanation text not null default '',
  difficulty text not null default 'medium' check (difficulty in ('easy', 'medium', 'hard')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.fill_in_blanks (
  id bigint generated by default as identity primary key,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  title text not null,
  content text not null,
  blanks text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.exam_results (
  id bigint generated by default as identity primary key,
  user_id text,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  score numeric not null default 0,
  total_questions integer not null default 0,
  correct_answers integer not null default 0,
  time_spent integer not null default 0,
  completed_at timestamptz not null default now()
);

create table if not exists public.fill_blank_results (
  id bigint generated by default as identity primary key,
  user_id text,
  fill_blank_id bigint not null references public.fill_in_blanks(id) on delete cascade,
  score numeric not null default 0,
  total_blanks integer not null default 0,
  correct_blanks integer not null default 0,
  completed_at timestamptz not null default now()
);

create index if not exists idx_subjects_category_id on public.subjects(category_id);
create index if not exists idx_questions_subject_id on public.questions(subject_id);
create index if not exists idx_fill_in_blanks_subject_id on public.fill_in_blanks(subject_id);
create index if not exists idx_exam_results_subject_id on public.exam_results(subject_id);
create index if not exists idx_fill_blank_results_fill_blank_id on public.fill_blank_results(fill_blank_id);

-- The app uses the server-only service-role key. RLS prevents accidental public access.
alter table public.categories enable row level security;
alter table public.subjects enable row level security;
alter table public.questions enable row level security;
alter table public.fill_in_blanks enable row level security;
alter table public.exam_results enable row level security;
alter table public.fill_blank_results enable row level security;
